baseURL = 'https://zvazvedu.cz/'
languageCode = 'cs-cz'
title = 'Zvaž vědu!'
uglyURLs = false
enableEmoji = true
[params]
    description = 'Oficiální stránky Zvaž vědu!'
[markup.goldmark.renderer]
    unsafe = true